# Site Config
name: "IBM Typography"
description: More sensible software typography for IBM
baseurl: "/mcpaul/duo-product-type"
url: https://github.ibm.com/mcpaul/duo-product-type.git

# Build Settings
markdown: kramdown
highlighter: true
permalink: pretty

# In/ Excludes
include: [".htaccess"]
exclude: ["node_modules", "gulpfile.js", "Gemfile", "Gemfile.lock", ".jekyll-metadata", "commit-hook.sh", "package.json", "local_config.yml", "README.md", "package-lock.json"]

# Plugins
assets:
  digest: true
  cache: false
  sources:
    - "_site/assets"

# Read and Output Collections
collections:
  collection:
    output: true
    permalink: /collection/:path/
